apiVersion: v1
kind: Service
metadata:
  name: readcsv-nodeport-service

spec:
  type: NodePort
  selector:
    app: readcsv-api
  ports:
   - name: readcsv-nodeport-service-name
     port: 80
     targetPort: 80
     nodePort: 30008
